spring:
  application:
    name: garden
  datasource:
    url: jdbc:postgresql://localhost:9000/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: maria17
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        generate_statistics: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
  flyway:
    baseline-on-migrate: true
    baseline-description: "init"
    baseline-version: 0
    enabled: true
    user: postgresql
    password: maria17
logging:
  level:
    org:
      hibernate:
        stat: debug
        type: trace
