spring:
  application:
    name: garden
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        generate_statistics: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:9000/postgres
    username: postgres
    password: maria17
    driver-class-name: org.postgresql.Driver

logging:
  level:
    org:
      hibernate:
        stat: debug
        type: trace
